[server]
host: 0.0.0.0
port: 7125
klippy_uds_address: /home/pi/printer_data/comms/klippy.sock

[file_manager]
enable_object_processing: True

[authorization]
trusted_clients:
    10.0.0.0/8
    127.0.0.0/8
    169.254.0.0/16
    172.16.0.0/12
    192.168.0.0/16
    FE80::/10
    ::1/128
cors_domains:
    *.lan
    *.local
    *.internal
    *://localhost
    *://localhost:*
    *://my.mainsail.xyz
    *://app.fluidd.xyz

[octoprint_compat]

[history]

[analysis]
platform: auto
#   The platform flavor of Klipper Estimator to use.  Must be a choice
#   from rpi, linux, osx, and auto. Note that "rpi" supports armv7 and
#   aarch64 linux platforms, whereas "linux" supports amd64 linux
#   platform.  The auto choice will attempt to automatically determine
#   the correct platform.  The default is auto.
# estimator_config: printer.cfg
#   A path relative to the "config" root specifying a config
#   file to use for Klipper Estimator.  The default is to
#   use a configuration dumped with data retrieved from Klipper's
#   current settings.
auto_dump_default_config: true
#   When set to true the default configuration for Klipper Estimator
#   will be dumped every time Klippy restarts.  When false the
#   configuration is only dumped if the default configuration file
#   does not exist.  The default is false.
estimator_timeout: 600
#   The maximum amount of time (in seconds) Klipper Estimator
#   is given to process a gcode file before processing is
#   aborted.  The default is 600 seconds.
enable_auto_analysis: true
#   When set to true Klipper Estimator will be used to perform a
#   post-process on gcode files immediately prior to metadata extraction.
#   The post-process will update the time estimate and M73 commands present
#   in the gcode file.  This automates the time analysis for any event
#   that triggers metadata processing.   Default is false.
enable_estimator_updates: true
#   When true Moonraker will create and register an entry for
#   klipper_estimator with the update manager.  Default is false.
enabled_processors = klipper_estimator

[update_manager]
channel: dev
refresh_interval: 168

[update_manager mainsail-config]
type: git_repo
primary_branch: master
path: ~/mainsail-config
origin: https://github.com/mainsail-crew/mainsail-config.git
managed_services: klipper

[update_manager mainsail]
type: web
channel: stable
repo: mainsail-crew/mainsail
path: ~/mainsail

[spoolman]
server: http://192.168.1.25:7912


[update_manager Spoolman]
type: zip
channel: stable
repo: Donkie/Spoolman
path: /home/pi/Spoolman
virtualenv: .venv
requirements: requirements.txt
persistent_files:
  .venv
  .env
managed_services: Spoolman


# Crowsnest update_manager entry
[update_manager crowsnest]
type: git_repo
path: ~/crowsnest
origin: https://github.com/mainsail-crew/crowsnest.git
managed_services: crowsnest
install_script: tools/pkglist.sh


[update_manager afc-software]
type: git_repo
path: ~/AFC-Klipper-Add-On
origin: https://github.com/ArmoredTurtle/AFC-Klipper-Add-On.git
managed_services: klipper
primary_branch: main
is_system_service: False
info_tags:
    desc=AFC Klipper Add On

## Klippain Shake&Tune automatic update management
[update_manager Klippain-ShakeTune]
type: git_repo
origin: https://github.com/Frix-x/klippain-shaketune.git
path: ~/klippain_shaketune
virtualenv: /home/pi/klippy-env
requirements: requirements.txt
system_dependencies: system-dependencies.json
primary_branch: main
managed_services: klipper
